"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Orc = exports.Halfling = exports.Elf = exports.Dwarf = void 0;
const Race_1 = require("./Race");
var Dwarf_1 = require("./Dwarf");
Object.defineProperty(exports, "Dwarf", { enumerable: true, get: function () { return Dwarf_1.default; } });
var Elf_1 = require("./Elf");
Object.defineProperty(exports, "Elf", { enumerable: true, get: function () { return Elf_1.default; } });
var Halfling_1 = require("./Halfling");
Object.defineProperty(exports, "Halfling", { enumerable: true, get: function () { return Halfling_1.default; } });
var Orc_1 = require("./Orc");
Object.defineProperty(exports, "Orc", { enumerable: true, get: function () { return Orc_1.default; } });
exports.default = Race_1.default;
